version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: order-mongo
    ports:
      - "27018:27017"  # Host:Container port mapping
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=order_db
    volumes:
      - mongo_data:/data/db
    networks:
      - order-network

  # Order Service
  order-svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "50054:50054"
    env_file:
      - .env  
    depends_on:
      - mongo
    networks:
      - order-network

volumes:
  mongo_data:

networks:
  order-network:
    driver: bridge 